Finduk.Application/Models/DailyPriceViewModel.cs
using System;
using Finduk.Application.Base;

namespace Finduk.Application.Models
{
    public class DailyPriceViewModel:ModelBase
    {
        public Int32 id { get; set; }
        public ProductViewModel product { get; set; }
        public DateTime daily_date { get; set; }
        public double price { get; set; }
        public Int32 currency { get; set; }
        public UserViewModel insert_user { get; set; }
        public DateTime insert_date { get; set; }
    }
}

Finduk.Application/Controllers/DailyPriceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finduk.Application.Base;
using Finduk.Application.Models;
using Microsoft.AspNetCore.Mvc;


namespace Finduk.Application.Controllers
{
    public class DailyPriceController : BaseController
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.PageTitle = "Günlük Fiyat";
            ViewBag.PageTitleDescription = "Günlük Fiyatların listesi";
            ViewBag.NavigationInfo = "Günlük Fiyat";
            return View();
        }

        public IActionResult Definition(DailyPriceViewModel model)
        {
            return PartialView(model);
        }
    }
}

Finduk.Application/Views/DailyPrice/Definition.cshtml
@model DailyPriceViewModel;
@{
    var transcationCode = Finduk.Application.Base.ApiMethod.DailyPrices;
    var formId = transcationCode + "FormModal";
}
<div class="modal fade" id="@formId" tabindex="-1" role="dialog" aria-labelledby="contactFormModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        @using (Html.BeginForm("Definition", "DailyPrice", FormMethod.Post, new { id = "template-contactform", name = "template-contactform", @class = "nobottommargin" }))
        {
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="contactFormModalLabel">Günlük Ürün Fiyatı Tanımlama</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">

                <div class="form-widget">

                    <div class="form-result"></div>

                    <div class="col_half">
                        <label for="template-contactform-name">Ürün <small>*</small></label>
                        @Html.DropDownListFor(Model => Model.product.id, Model.ProductListItems, new { id = "product", name = "template-contactform-product", @class = "select-1 form-control required" })
                    </div>

                    <div class="col_half col_last">
                        <label for="template-contactform-name">Tarih <small>*</small></label>
                        <input type="text" class="form-control datetimepicker-input tleft" data-toggle="datetimepicker" autocomplete="off" id="daily_date" data-target="#daily_date" />
                    </div>

                    <div class="clear"></div>
                    <div class="col_half">
                        <label for="template-contactform-price">Fiyat <small>*</small></label>
                        @Html.TextBoxFor(Model => Model.price, new { id = "price", name = "template-contactform-price", @class = "sm-form-control required" })
                    </div>
                    <div class="col_half col_last">
                        <label for="template-contactform-currency">Döviz Tipi <small>*</small></label>
                        @Html.DropDownListFor(Model => Model.currency, Model.CurrencyListItems, new { id = "currency", name = "template-contactform-currency", @class = "select-1 form-control required" })
                    </div>

                    <input type="hidden" name="prefix" value="template-contactform-">
                </div>

            </div>
            <div class="modal-footer">
                <div class="col-12 d-flex justify-content-end align-items-center">
                    @if (Model.id > 0)
                    {
                        <button class="btn btn-success ml-2" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Güncelle</button>
                    }
                    else
                    {
                        <button class="btn btn-success ml-2" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Kaydet</button>
                    }
                </div>
            </div>
        </div>

        <!-- /.modal-content -->
        }

    </div><!-- /.modal-dialog -->
</div>


<script>
    $("form").submit(function (event) {
        event.preventDefault();
        formSubmitHandler();
    });
    $('#daily_date').datetimepicker({
        locale: {
            format: 'MM/DD/YYYY h:mm A'
        },
    });
</script>

Finduk.Application/Views/DailyPrice/Index.cshtml

@{
    var transcationCode = Finduk.Application.Base.ApiMethod.DailyPrices;
}

@await Html.PartialAsync("Title")
<section id="content">
    <div class="container clearfix">
        <div class="content-wrap">
            <div class="fancy-title title-dotted-border title-center">
                <h2><span>Günlük Fiyat</span> Bilgisi</h2>
            </div>
            <div class="container clearfix">
                <div id='@transcationCode'></div>
            </div>
        </div>
    </div>
</section>
<script>
    var formSubmitHandler = $.noop;
    $(window).load(function () {
    showGrid('@transcationCode');
        function showGrid(transcationCode) {
            var grid = $('#' + transcationCode);
            var getUrl = baseUrl + transcationCode + "/";
            var postUrl = baseUrl + transcationCode + "/new/";
            var currencyList = @Json.Serialize(ApplicationContext.Currency);
            var latestJsGridOptions = Object.assign(jsGridDefaultOptions, {
                inserting: false,
                editing: false,
                filtering: true,
                sorting: true,
                controller:
                {
                    loadData: function (filter) {
                        var result = callAPI(getUrl, null, "GET");
                        var d = $.Deferred();

                        if (result && result[transcationCode]) {
                            return {
                                data: result[transcationCode],
                                itemsCount: [result[transcationCode].length - 1]
                            }
                        }
                        else {
                            return {
                                data: [],
                                itemsCount: [0]
                            }
                        }
                    },
                    insertItem: function (item) {
                        delete item.id;
                        var insertData = JSON.stringify(item);
                        var result = callAPI(postUrl, insertData, "POST");
                    },
                    updateItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var updateItem = JSON.stringify(item);
                        var result = callAPI(url, updateItem, "PUT");
                    },
                    deleteItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var result = callAPI(url, null, "DELETE");
                    }
                },
                rowClick: function (args) {
                    //showDetailsDialog("Update", args.item);
                },
                fields: [
                    { name: "id", type: "number", visible: false, width: "auto" },
                    { title: "Ürün Adı", name: "product.name", type: "text", validate: "required", width: "auto" },
                    { title: "Fiyat", name: "price", type: "text", validate: "required", width: "auto" },
                    { title: "Döviz Tipi", name: "currency", type: "select", items: currencyList, valueField: "id", textField: "text", validate: "required", width: "auto" },
                    { title: "Tarihi", name: "daily_date", type: "customDateTimeField", validate: "required", width: "auto" },
                    {
                        type: "control",
                        width: 120,
                        modeSwitchButton: false,
                        editButton: false,
                        headerTemplate: function ()
                        {
                            return $("<button>")
                                .attr("type", "button")
                                .attr("class", "button button-rounded button-reveal button-large button-yellow button-light")
                                .append("<i class='icon-edit'></i>")
                                .append("<span>Yeni</span>")
                                .on("click", function () {
                                    var item = {};
                                    showDetailsDialog("Add", item);
                                });
                        }
                    }
                ]
            });

            grid.jsGrid(latestJsGridOptions);
            var showDetailsDialog = function (dialogType, item) {
                $.post('/DailyPrice/Definition/', item, function (content) {
                    showModal('@transcationCode', content);
                    formSubmitHandler = function () {
                        saveClient(item, dialogType === "Add");
                    };
                });
            };
            var saveClient = function (item, isNew) {
                var postItem = {};
                $.extend(postItem, {
                    product: $("#product").val(),
                    price: $("#price").val(),
                    currency: $("#currency").val(),
                    daily_date: $("#daily_date").val()
                });
                postItem.insert_user = 1;
                if (!isNew) {
                    postItem.id = item.id;
                }

                postItem.daily_date = new Date(postItem.daily_date).toISOString();
                grid.jsGrid(isNew ? "insertItem" : "updateItem", postItem);
                $('#' + transcationCode + 'FormModal').modal('hide');
                $('#' + transcationCode + 'FormModal').empty();
            };
        }
    });
</script>