Finduk.Application/Models/ContactViewModel.cs
using System;
using Finduk.Application.Base;

namespace Finduk.Application.Models
{
    public class ContactViewModel : ModelBase
    {
        public Int32 id { get; set; }
        public string title { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public CompanyViewModel company { get; set; }
        public bool is_owner { get; set; }
        public CountryViewModel country { get; set; }
        public CityViewModel city { get; set; }
        public string description { get; set; }
        public bool is_active { get; set; }
        public UserViewModel insert_user { get; set; }
        public DateTime insert_date { get; set; }
        public UserViewModel contact_user { get; set; }
    }
}

Finduk.Application/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Finduk.Application.Models;
using Finduk.Application.Base;
namespace Finduk.Application.Controllers
{
    public class ContactController : BaseController
    {
        public IActionResult Index()
        {
            ViewBag.PageTitle = "Kişiler";
            ViewBag.PageTitleDescription = "İş yapılan kişi yada kurumlar";
            ViewBag.NavigationInfo = "Kişiler";
            return View();
        }
        public IActionResult Definition(ContactViewModel model)
        {
            return PartialView(model);
        }
    }
}

Finduk.Application/Views/Contact/Definition.cshtml
@model ContactViewModel;
@{
    var transcationCode = Finduk.Application.Base.ApiMethod.Contact;
    var formId = transcationCode + "FormModal";
}
<div class="modal fade" id="@formId" tabindex="-1" role="dialog" aria-labelledby="contactFormModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        @using (Html.BeginForm("Definition", "Contact", FormMethod.Post, new { id = "template-contactform", name = "template-contactform", @class = "nobottommargin" }))
        {
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="contactFormModalLabel">Bağlantı Tanımlama</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">

                    <div class="form-widget">

                        <div class="form-result"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Adı <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.first_name, new { id = "contactFirstName", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-name">Soyadı <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.last_name, new { id = "contactLastName", name = "template-contactform-name", @class = "sm-form-control" })
                        </div>

                        <div class="clear"></div>
                        <div class="col_half">
                            <label for="template-contactform-name">Ünvan <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.title, new { id = "contactTitle", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-phone">Telefon <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.phone, new { id = "contactPhone", name = "template-contactform-phone", @class = "sm-form-control" })
                        </div>

                        <div class="clear"></div>
                        <div class="col_half">
                            <label for="template-contactform-name">Mail <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.email, new { id = "contactMail", name = "template-contactform-name", @class = "sm-form-control" })
                        </div>
                        <div class="col_half col_last">
                            <label for="template-contactform-name">Şirket <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.contact_user.id, Model.ContactUserItems, new { id = "contact_user", @class = "select-1 form-control required" })
                        </div>


                        <div class="clear"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Aktif mi? <small>*</small></label>
                            @Html.CheckBoxFor(Model => Model.is_active, new { id = "contactIsActive", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>
                        <div class="col_half col_last">
                            <label for="template-contactform-name">Sahibi mi? <small>*</small></label>
                            @Html.CheckBoxFor(Model => Model.is_owner, new { id = "contactIsOwner", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>

                        <div class="clear"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Ülke <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.country.id, Model.CountryListItems, new { id = "contactCountryId", @class = "select-1 form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-name">Şehir <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.city.id, Model.CompanyCityListItems, new { id = "contactCityId", @class = "select-1 form-control required" })
                        </div>

                        <div class="clear"></div>
                        <div class="col_half ">
                            <label for="template-contactform-name">Şirket <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.company.id, Model.CompanyListItems, new { id = "contactCompanyId", @class = "select-1 form-control required" })
                        </div>
                        
                        <div class="col_half col_last">
                            <label for="template-contactform-name">Açıklama <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.description, new { id = "contactDescription", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>


                        <input type="hidden" name="prefix" value="template-contactform-">
                    </div>

                </div>
                <div class="modal-footer">
                    <div class="col-12 d-flex justify-content-end align-items-center">
                        @if (Model.id > 0)
                        {
                            <button class="btn btn-success ml-2" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Güncelle</button>
                        }
                        else
                        {
                            <button class="btn btn-success ml-2" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Kaydet</button>
                        }
                    </div>
                </div>
            </div>

            <!-- /.modal-content -->
        }

    </div><!-- /.modal-dialog -->
</div>


<script>$("form").submit(function (event) {
        event.preventDefault();
        formSubmitHandler();
    });</script>

Finduk.Application/Views/Contact/Index.cshtml

@{
    var transcationCode = Finduk.Application.Base.ApiMethod.Contact;
}

@await Html.PartialAsync("Title")
<section id="content">
    <div class="container clearfix">
        <div class="content-wrap">
            <div class="fancy-title title-dotted-border title-center">
                <h2><span>Bağlantı</span> Bilgisi</h2>
            </div>
            <div class="container clearfix">
                <div id='@transcationCode'></div>
            </div>
        </div>
    </div>
</section>
<script>
    var formSubmitHandler = $.noop;
    $(window).load(function () {
    showGrid('@transcationCode');
        function showGrid(transcationCode) {
            var grid = $('#' + transcationCode);
            var getUrl = baseUrl + transcationCode + "/";
            var postUrl = baseUrl + transcationCode + "/new/";
            var latestJsGridOptions = Object.assign(jsGridDefaultOptions, {
                inserting: false,
                editing: false,
                filtering: true,
                sorting: true,
                controller:
                {
                    loadData: function (filter) {
                        var result = callAPI(getUrl, null, "GET");
                        var d = $.Deferred();

                        if (result && result[transcationCode]) {
                            return {
                                data: result[transcationCode],
                                itemsCount: [result[transcationCode].length - 1]
                            }
                        }
                        else {
                            return {
                                data: [],
                                itemsCount: [0]
                            }
                        }
                    },
                    insertItem: function (item) {
                        delete item.id;
                        var insertData = JSON.stringify(item);
                        var result = callAPI(postUrl, insertData, "POST");
                    },
                    updateItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var updateItem = JSON.stringify(item);
                        var result = callAPI(url, updateItem, "PUT");
                    },
                    deleteItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var result = callAPI(url, null, "DELETE");
                    }
                },
                rowClick: function (args) {
                    showDetailsDialog("Update", args.item);
                },
                fields: [
                    { name: "id", type: "number", visible: false, width: "auto" },
                    { title: "Ünvanı", name: "title", type: "text", validate: "required", width: "auto" },
                    { title: "Adı", name: "first_name", type: "text", validate: "required", width: "auto" },
                    { title: "Soyadı", name: "last_name", type: "text", validate: "required", width: "auto" },
                    { title: "Açıklama", name: "description", type: "text", validate: "required", width: "auto" },
                    {
                        type: "control",
                        width: 120,
                        modeSwitchButton: false,
                        editButton: false,
                        headerTemplate: function ()
                        {
                            return $("<button>")
                                .attr("type", "button")
                                .attr("class", "button button-rounded button-reveal button-large button-yellow button-light")
                                .append("<i class='icon-edit'></i>")
                                .append("<span>Yeni</span>")
                                .on("click", function () {
                                    var item = {};
                                    showDetailsDialog("Add", item);
                                });
                        }
                    }
                ]
            });

            grid.jsGrid(latestJsGridOptions);
            var showDetailsDialog = function (dialogType, item) {
                $.post('/Contact/Definition/', item, function (content) {
                    showModal('@transcationCode', content);
                    formSubmitHandler = function () {
                        saveClient(item, dialogType === "Add");
                    };
                });
            };
            var saveClient = function (item, isNew) {
                var postItem = {};
                $.extend(postItem, {
                    title: $("#contactTitle").val(),
                    first_name: $("#contactFirstName").val(),
                    last_name: $("#contactLastName").val(),
                    email: $("#contactMail").val(),
                    phone: $("#contactPhone").val(),
                    company: $("#contactCompanyId").val(),
                    is_owner: $("#contactIsOwner").is(":checked"),
                    is_active: $("#contactIsActive").is(":checked"),
                    country: $("#contactCountryId").val(),
                    city: $("#contactCityId").val(),
                    contact_user: $("#contact_user").val(),
                    description: $("#contactDescription").val()
                });
                postItem.insert_user = 1;
                if (!isNew) {
                    postItem.id = item.id;
                }
                grid.jsGrid(isNew ? "insertItem" : "updateItem", postItem);
                $('#' + transcationCode + 'FormModal').modal('hide');
                $('#' + transcationCode + 'FormModal').empty();
            };
        }
    });
</script>