Finduk.Application/Models/WayBillViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Finduk.Application.Base;

namespace Finduk.Application.Models
{
    public class WayBillViewModel:ModelBase
    {
        public Int32 id { get; set; }
        public string waybill_no { get; set; }
        public string waybill_type { get; set; }
        public string status { get; set; }
        public Int32 contactId { get; set; }
        public ContactViewModel contact { get; set; }
        public Int32 companyId { get; set; }
        public CompanyViewModel company { get; set; }
        public string serial_no { get; set; }
        public string order_no { get; set; }
        public string description { get; set; }
        public string waybill_url { get; set; }
        public DateTime? dispatch_date { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy H:mm tt}")]
        public DateTime delivery_date { get; set; }
        public UserViewModel insert_user { get; set; }
        public DateTime insert_date { get; set; }
        public Int32 productId { get; set; }
        public ProductViewModel product { get; set; }
        public int store { get; set; }
        public int quantity { get; set; }
        public int quantity_type { get; set; }
    }
}

Finduk.Application/Controllers/WayBillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Finduk.Application.Base;
using Finduk.Application.Models;
using Microsoft.AspNetCore.Mvc;

namespace Finduk.Application.Controllers
{
    public class WayBillController : BaseController
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.PageTitle = "İrsaliye";
            ViewBag.PageTitleDescription = "Çıkış yada Giriş bilgileri";
            ViewBag.NavigationInfo = "İrsaliye";
            return View();
        }
        public IActionResult Definition(WayBillViewModel model)
        {
            return PartialView(model);
        }
    }
}

Finduk.Application/Views/WayBill/Definition.cshtml
@model WayBillViewModel;
@{
    var transcationCode = Finduk.Application.Base.ApiMethod.Waybill;
    var formId = transcationCode + "FormModal";
    Model.delivery_date = DateTime.Now;
    Model.dispatch_date = DateTime.Now;
}

<div class="modal fade" id="@formId" tabindex="-1" role="dialog" aria-labelledby="contactFormModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        @using (Html.BeginForm("Definition", "WayBill", FormMethod.Post, new { id = "template-contactform", name = "template-contactform", @class = "nobottommargin" }))
        {
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="contactFormModalLabel">İrsaliye Tanımlama</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">

                    <div class="form-widget">

                        <div class="form-result"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">İrsaliye No <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.waybill_no, new { id = "waybill_no", name = "template-contactform-name", @class = "sm-form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-name">İrsaliye Tipi <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.waybill_type, Model.WayBillTypeListItems, new { id = "waybill_type", @class = "select-1 form-control required" })
                        </div>

                        <div class="clear"></div>
                        <div class="col_half">
                            <label for="template-contactform-phone">Şirketler <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.company.id, Model.CompanyListItems, new { id = "company", @class = "select-1 form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-name">Kişiler <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.contact.id, Model.ContactListItems, new { id = "contact", @class = "select-1 form-control required" })
                        </div>

                        <div class="clear"></div>
                        <div class="col_half">
                            <label for="template-contactform-name">Seri No <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.serial_no, new { id = "serial_no", @class = "sm-form-control" })
                        </div>


                        <div class="col_half col_last">
                            <label for="template-contactform-name">Sipariş No <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.order_no, new { id = "order_no", @class = "sm-form-control" })
                        </div>

                        <div class="clear"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Ürünler <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.product.id, Model.ProductListItems, new { id = "product", @class = "select-1 form-control required" })
                        </div>
                        <div class="col_half col_last">
                            <label for="template-contactform-name">Ürünler Türü <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.quantity_type, Model.QuantityTypeListItems, new { id = "quantity_type", @class = "select-1 form-control required" })
                        </div>

                        <div class="clear"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Depo <small>*</small></label>
                            @Html.DropDownListFor(Model => Model.store, Model.StoreListItems, new { id = "store", @class = "select-1 form-control required" })
                        </div>

                        <div class="col_half col_last">
                            <label for="template-contactform-name">Miktar <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.quantity, new { id = "quantity", @class = "sm-form-control required" })
                        </div>
                        <div class="clear"></div>

                        <div class="col_half">
                            <label for="template-contactform-name">Sevk Tarihi <small>*</small></label>
                            <input type="text" class="form-control datetimepicker-input tleft" data-toggle="datetimepicker" autocomplete="off" id="dispatch_date" data-target="#dispatch_date" />
                        </div>
                        <div class="col_half col_last">
                            <label for="template-contactform-name">Teslim Tarihi <small>*</small></label>
                            <input type="text" class="form-control datetimepicker-input tleft" data-toggle="datetimepicker" autocomplete="off" id="delivery_date"  data-target="#delivery_date" />
                        </div>
                        <div class="clear"></div>

                        <div class="col_full">
                            <label for="template-contactform-name">Açıklama <small>*</small></label>
                            @Html.TextBoxFor(Model => Model.description, new { id = "description", @class = "sm-form-control required" })
                        </div>
                        <div class="clear"></div>
                        <input type="hidden" name="prefix" value="template-contactform-">
                    </div>

                        </div>
                        <div class="modal-footer">
                            <div class="col-12 d-flex justify-content-end align-items-center">
                                @if (Model.id > 0)
                                {
                                    <button class="button button-3d nomargin" type="submit" id="template-contactform-submit" value="submit">Güncelle</button>
                                }
                                else
                                {
                                    <button class="button button-3d nomargin" type="submit" id="template-contactform-submit" value="submit">Kaydet</button>
                                }
                            </div>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                }

            </div><!-- /.modal-dialog -->
        </div>


<script>$("form").submit(function (event) {
    event.preventDefault();
    debugger;
    if ($("#waybill_type").val() != "Seçiniz" &&
        $("#contact").val() != "Seçiniz" &&
        $("#company").val() != "Seçiniz" &&
        $("#store").val() != "Seçiniz" &&
        $("#product").val() != "Seçiniz" &&
        $("#waybill_no").val() &&
        $("#serial_no").val() &&
        $("#order_no").val() &&
        $("#description").val() &&
        $("#dispatch_date").val() &&
        $("#delivery_date").val() &&
        $("#quantity").val() != "0" &&
        $("#quantity").val() != "" &&
        $("#quantity_type").val()  ) {
        formSubmitHandler();
    }
    else {
        showStatusMessage(" Lütfen boş alanları doldurunuz.", MessageType.Information);
    }
    });

    $(function () {
        $('#dispatch_date').datetimepicker({
            locale: {
                format: 'MM/DD/YYYY h:mm A'
            },
        });
        $('#delivery_date').datetimepicker({
            locale: {
                format: 'MM/DD/YYYY h:mm A'
            },
        });
    });</script>

Finduk.Application/Views/WayBill/Index.cshtml

@{
    var transcationCode = Finduk.Application.Base.ApiMethod.Waybill;
}

@await Html.PartialAsync("Title")
<section id="content">
    <div class="container clearfix">
        <div class="content-wrap">
            <div class="fancy-title title-dotted-border title-center">
                <h2><span>İrsaliye</span> Bilgisi</h2>
            </div>
            <div class="container clearfix">
                <div id='@transcationCode'></div>
            </div>
        </div>
    </div>
</section>

<script>
    var formSubmitHandler = $.noop;
    $(window).load(function () {
    showGrid('@transcationCode');
        function showGrid(transcationCode) {
            var grid = $('#' + transcationCode);
            var getUrl = baseUrl + transcationCode + "/";
            var postUrl = baseUrl + transcationCode + "/new/";
            var waybillTypeList = @Json.Serialize(ApplicationContext.FinanceType);
            var unitTypeList = @Json.Serialize(ApplicationContext.QuantityType);
            var latestJsGridOptions = Object.assign(jsGridDefaultOptions, {
                inserting: false,
                editing: false,
                filtering: true,
                sorting: true,
                controller:
                {
                    loadData: function (filter) {
                        var result = callAPI(getUrl, null, "GET");
                        var d = $.Deferred();

                        if (result && result[transcationCode]) {
                            return {
                                data: result[transcationCode],
                                itemsCount: [result[transcationCode].length - 1]
                            }
                        }
                        else {
                            return {
                                data: [],
                                itemsCount: [0]
                            }
                        }
                    },
                    insertItem: function (item) {
                        delete item.id;
                        var insertData = JSON.stringify(item);
                        var result = callAPI(postUrl, insertData, "POST");
                    },
                    updateItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var updateItem = JSON.stringify(item);
                        var result = callAPI(url, updateItem, "PUT");
                    },
                    deleteItem: function (item) {
                        var url = getUrl + item.id + '/';
                        var result = callAPI(url, null, "DELETE");
                    }
                },
                rowClick: function (args) {
                    showDetailsDialog("Update", args.item);
                },
                fields: [
                    { name: "id", type: "number", visible: false, width: "auto" },
                    { title: "İrsaliye No", name: "waybill_no", type: "text", validate: "required", width: "auto" },
                    { title: "İrsaliye Tipi", name: "waybill_type", type: "select", items: waybillTypeList, valueField: "id", textField: "text", validate: "required", width: "auto" },
                    { title: "Seri No", name: "serial_no", type: "text", validate: "required", width: "auto" },
                    { title: "Sipariş No", name: "order_no", type: "text", validate: "required", width: "auto" },
                    { title: "Açıklama", name: "description", type: "text", validate: "required", width: "auto" },
                    { title: "Miktar", name: "quantity", type: "text", validate: "required", width: "auto" },
                    { title: "Miktar Tipi", name: "quantity_type", type: "select", items: unitTypeList, valueField: "id", textField: "text", validate: "required", width: "auto" },
                    {
                        type: "control",
                        width: 120,
                        modeSwitchButton: false,
                        editButton: false,
                        headerTemplate: function ()
                        {
                            return $("<button>")
                                .attr("type", "button")
                                .attr("class", "button button-rounded button-reveal button-large button-yellow button-light")
                                .append("<i class='icon-edit'></i>")
                                .append("<span>Yeni</span>")
                                .on("click", function () {
                                    var item = {};
                                    showDetailsDialog("Add", item);
                                });
                        }
                    }
                ]
            });

            grid.jsGrid(latestJsGridOptions);
            var showDetailsDialog = function (dialogType, item) {
                $.post('/WayBill/Definition/', item, function (content) {
                    showModal('@transcationCode', content);
                    formSubmitHandler = function () {
                        saveClient(item, dialogType === "Add");
                    };
                });
            };
            var saveClient = function (item, isNew) {
                var postItem = {};
                $.extend(postItem, {
                    waybill_type: $("#waybill_type").val(),
                    waybill_no: $("#waybill_no").val(),
                    contact: $("#contact").val(),
                    company: $("#company").val(),
                    serial_no: $("#serial_no").val(),
                    order_no: $("#order_no").val(),
                    description: $("#description").val(),
                    dispatch_date: $("#dispatch_date").val(),
                    delivery_date: $("#delivery_date").val(),
                    product: $("#product").val(),
                    quantity: $("#quantity").val(),
                    quantity_type: $("#quantity_type").val(),
                    store: $("#store").val()
                });
                postItem.insert_user = 1;
                if (!isNew) {
                    postItem.id = item.id;
                }
                postItem.status = 1;
                postItem.dispatch_date = new Date(postItem.dispatch_date).toISOString();
                postItem.delivery_date = new Date(postItem.delivery_date).toISOString();
                grid.jsGrid(isNew ? "insertItem" : "updateItem", postItem);
                $('#' + transcationCode + 'FormModal').modal('hide');
                $('#' + transcationCode + 'FormModal').empty();
            };
        }
    });
</script>